#Uncomment port 5005 to enable debugging
version: '2.4'

networks:
    backend-network:
        driver: bridge


services:
  postgres-db-service:
    image: ${DB_IMAGE_VERSION:-postgres:16.1}
    container_name: postgres
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-0000}
    volumes:
      - ./backend/data:/docker-entrypoint-initdb.d
    networks:
      - backend-network


  eureka-server:
    container_name: eureka-server
    build: backend/eureka-server
    image: ${EUREKA_SERVER_NAME:-eureka-server}
    env_file:
    - ./backend/eureka-server/.env.${ENVIRONMENT:-dev}
    restart: unless-stopped
    ports:
      - ${EUREKA_SERVER_PORT:-8761}:8761
    networks:
        - backend-network


  umbrella-service:
    container_name: umbrella-service
    build: backend/umbrella-service
    image: ${UMBRELLA_SERVICE_IMAGE:-umbrella-service}
    env_file:
      - ./backend/umbrella-service/.env.${ENVIRONMENT:-dev}
    restart: unless-stopped
    ports:
      - ${UMBRELLA_PORT:-0}:8080
    depends_on:
      - postgres-db-service
      - eureka-server
    networks:
      - backend-network

  user-service:
    container_name: user-service
    build: backend/user-service
    image: ${UMBRELLA_SERVICE_IMAGE:-user-service}
    env_file:
      - ./backend/user-service/.env.${ENVIRONMENT:-dev}
    restart: unless-stopped
    ports:
      - ${UMBRELLA_PORT:-0}:8080
    depends_on:
      - postgres-db-service
      - eureka-server
    networks:
      - backend-network

  auth-service:
    container_name: auth-service
    build: backend/auth-service
    image: ${AUTH_SERVICE_IMAGE:-auth-service}
    env_file:
      - ./backend/auth-service/.env.${ENVIRONMENT:-dev}
    restart: unless-stopped
    ports:
      - ${AUTH_SERVICE_PORT:-0}:8080
    depends_on:
      - postgres-db-service
      - eureka-server
    networks:
      - backend-network

  api-gateway:
    container_name: api-gateway
    build: backend/api-gateway
    image: ${API_GATEWAY_IMAGE:-api-gateway}
    env_file:
      - ./backend/api-gateway/.env.${ENVIRONMENT:-dev}
    restart: unless-stopped
    ports:
      - ${API_GATEWAY_PORT:-0}:8080
    depends_on:
      - postgres-db-service
      - eureka-server
    networks:
      - backend-network
