
# SpringDoc Configuration

springdoc:

  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    configUrl: http://localhost:8080/v3/api-docs/swagger-config
    url: http://localhost:8080/v3/api-docs
    urls:
      - name: Umbrella Service
        url: http://localhost:8080/v3/api-docs
      - name: User Service
        url: http://localhost:8081/v3/api-docs
      - name: Auth Service
        url: http://localhost:8082/v3/api-docs




