
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: umbrella-service
          uri: lb://umbrella-service
          predicates:
            - Path=/umbrella/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1


      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka

server:
    port: ${API_GATEWAY_PORT:80}
logging:
    level:
      org.springframework.web: FALSE
